language: python
python:
  - 3.7
install:
  - sudo apt-get install pandoc
  - pip install sphinx==1.7.9 sphinx_rtd_theme nbsphinx IPython jupyter_client ipykernel
  - pip install matplotlib numpy pandas
  - pip install git+https://github.com/HTenkanen/sphinxcontrib-versioning.git
script: sphinx-versioning build source build/html
after_success:
  - ./push.sh
env:
  global:
    - secure: "K6vBZjAGRacK1mTYDU+vVtu/e0mTkD/TB9QAng5RTD4umsiPMHqyLUHgaR3O+/5U7NqKHfDbRcFIZWeA/0Zs5WHJn563+KzP6kh5QMuTDeYYBAh5ZCmls5ZOM0jA3OWfJNV+vgkoxZXL6e+NRa7nSaJM4q8gQbKLu0q69UPPcv4OWd/xhBrg5NPKHJ3HAh7ALoI0jvAAVrtbgPsILC9G3m66KOFuPo5q0UPNGb8NS5oty8OBEBs0FRDeYbIciHjHHKHxjEml9NJPrwzrsLLj+/DZLyK8OVyYvz4ELS3PQGIk3YNJZGnLmeyorPe+H4xscJ9cZEWPAFjcgVkj3KuFEuSS9HzZcQpckknbkBq8afEWlljvNuU8hzswptgLItQytnHmPJjVM+8qERPq9F9ZimE9/zsuKwKrc8SXkaaVLgELvP/27pNT85vi/UeyP89/p/JEqppvNTj9B2cspLb07CL3+cwqlA+yPzaPUR1fXpMT6LxEvldGEhJBz5fJxg8pG93PafyxGiEW9838xnWkMjE1Ki8M6Sv0hcuSn1A4RHzIUqIXMUuXY6SebvRyVoqyddHRgl0iWahUGfNv94GnSP3PU+TST+D1ZRyCf/phyGiQ7zlFxZ0kh0NkKGIL8gT2fLeIDe+ccM4IcoFh2zjVMdeF31yEVqze5xciQZ1gs7s="
